//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\oscar\Desktop\Nueva carpeta\Composicion.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ComposicionParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IComposicionVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.textComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextComp([NotNull] ComposicionParser.TextCompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] ComposicionParser.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] ComposicionParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] ComposicionParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTitle([NotNull] ComposicionParser.TitleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.h1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitH1([NotNull] ComposicionParser.H1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.h2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitH2([NotNull] ComposicionParser.H2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.h3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitH3([NotNull] ComposicionParser.H3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.bold"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBold([NotNull] ComposicionParser.BoldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.italic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItalic([NotNull] ComposicionParser.ItalicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.underline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnderline([NotNull] ComposicionParser.UnderlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.para"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPara([NotNull] ComposicionParser.ParaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef([NotNull] ComposicionParser.RefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] ComposicionParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable([NotNull] ComposicionParser.TableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>justText</c>
	/// labeled alternative in <see cref="ComposicionParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJustText([NotNull] ComposicionParser.JustTextContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>justCommand</c>
	/// labeled alternative in <see cref="ComposicionParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJustCommand([NotNull] ComposicionParser.JustCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>textWithCommand</c>
	/// labeled alternative in <see cref="ComposicionParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextWithCommand([NotNull] ComposicionParser.TextWithCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.refItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefItem([NotNull] ComposicionParser.RefItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.listItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListItem([NotNull] ComposicionParser.ListItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.tableRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableRow([NotNull] ComposicionParser.TableRowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ComposicionParser.tableCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableCell([NotNull] ComposicionParser.TableCellContext context);
}
